export { Navbar } from "./navbar";
export { HeroSection } from "./hero";
export { AboutSection } from "./about";
export { SkillsSection } from "./skills";
export { ExperienceSection } from "./experience";
export { ProjectsSection } from "./projects";
export { EducationSection } from "./education";
export { ContactSection } from "./contact";
export { Footer } from "./footer";
